# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
# This workflow will build Python wheel and test installation.

name: Build Python Package

on:
  merge_group:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:  # Allow manual triggers

jobs:
  build-pypi:
    name: Build Python Wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'

      - name: Install python-build and twine
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build setuptools twine wheel
          python -m pip list

      - name: Build the wheel
        run: |
          python setup.py bdist_wheel

      - name: Verify the distribution
        run: twine check --strict dist/*

      - name: List the contents of the wheel
        run: python -m zipfile --list dist/*.whl

      - name: Install the wheel
        run: |
          python -m pip install dist/*.whl

      - name: Test intall
        run: |
          python -c "import ai_edge_quantizer"
