# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/

name: Colab Tests (nightly)

on:
  schedule:
    - cron: "0 10 * * *" # 10am UTC (3am PST)
  workflow_dispatch:  # Allow manual triggers

jobs:
  run-colabs-nightly:
    name: Run Colabs Python Nightly
    runs-on: ubuntu-latest  # Specify a runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install papermill tensorflow-cpu ipykernel jupyter matplotlib torchvision scikit-image

      - name: Run Colab notebook
        run: |
          papermill colabs/getting_started.ipynb /tmp/out -k python3 -p visualize_model 0
          papermill colabs/torch_convert_and_quantize.ipynb /tmp/out -k python3 -p visualize_model 0
          papermill colabs/selective_quantization_isnet.ipynb /tmp/out -k python3 -p visualize_model 0


      - name: Create Issue on Failure
        if: failure() && github.event_name != 'workflow_dispatch'
        uses: JasonEtco/create-an-issue@v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/workflows/action_failure_issue_template.md